customhost = "myownproject.cxfyc0e4nios.us-east-1.rds.amazonaws.com"
customuser = "awsownproject"
custompass = "awsownproject"
customdb = "emploee"
custombucket = "addmyownproject"
customregion = "us-east-1"
